-- PostgreSQL. timestamptz stores the instant itself, independent of any time zone.
create table model_object
(
    id                integer generated by default as identity primary key,
    name              varchar(255) not null,
    description       text         not null,
    model_object_type varchar(32)  not null,
    deleted           boolean      not null default false,
    created           timestamptz(3) not null,
    last_updated      timestamptz(3) not null
);

create index model_object_name on model_object (name);
